name:           redundant100
version:        0.0.0
synopsis:       Redundant gene clustering
category:       Bioinformatics
license:        GPL-3
maintainer:     Luis Pedro Coelho <coelho@embl.de>
ghc-options:
  - -Wall
  - -Wcompat
  - -fwarn-tabs
  - -fno-warn-missing-signatures
  - -threaded
  - -O2
  - -fno-full-laziness
  - -fPIC
  - -funbox-strict-fields
  - -rtsopts
  - ! '"-with-rtsopts=-A128m -n8m -H -c"'


dependencies:
  - base >= 4.7 && < 5
  - async
  - bytestring
  - conduit
  - conduit-algorithms
  - conduit-extra
  - conduit-combinators
  - containers
  - deepseq
  - directory
  - exceptions
  - extra
  - filepath
  - filemanip
  - hashtables
  - primitive
  - inline-c
  - inline-c-cpp
  - MissingH
  - resourcet
  - temporary
  - text
  - transformers
  - transformers-base
  - safe
  - safeio
  - strict
  - stringsearch
  - vector
  - vector-algorithms


source-dirs:
  - ./src

executables:
  SortSizes:
    main: SortSizes.hs
    other-modules:
     - Data.BioConduit
     - Data.UnionFind

  SplitBlocks:
    main: SplitBlocks.hs
    other-modules:
     - Data.BioConduit
     - Data.UnionFind

  FindExactOverlaps:
    main: FindExactOverlaps.hs
    c-sources: src/FindExactOverlaps.cpp
    other-modules:
     - Data.BioConduit
     - Data.UnionFind

  RemoveRepeats:
    main: RemoveRepeats.hs
    other-modules:
     - Data.BioConduit
     - Data.UnionFind

  Remove:
    main: Remove.hs
    other-modules:
     - Data.BioConduit
     - Data.UnionFind

  MergeSizes:
    main: MergeSizes.hs
    other-modules:
     - Data.BioConduit
     - Data.UnionFind

