name:           redundant100
version:        0.0.0
synopsis:       Redundant gene clustering
category:       Bioinformatics
license:        GPL-3
maintainer:     Luis Pedro Coelho <coelho@embl.de>
ghc-options:    -Wall -O2 -threaded -fwarn-tabs

dependencies:
  - base >= 4.7 && < 5
  - async
  - bytestring
  - conduit
  - conduit-algorithms
  - conduit-extra
  - conduit-combinators
  - containers
  - data-hash
  - deepseq
  - directory
  - exceptions
  - extra
  - filepath
  - filemanip
  - hashtables
  - primitive
  - MissingH
  - resourcet
  - temporary
  - text
  - transformers
  - transformers-base
  - safe
  - safeio
  - strict
  - stringsearch
  - vector
  - vector-algorithms


source-dirs:
  - ./

executables:
  SortSizes:
    main: SortSizes.hs

  SplitBlocks:
    main: SplitBlocks.hs

  FindExactOverlaps:
    main: FindExactOverlaps.hs

  RemoveRepeats:
    main: RemoveRepeats.hs

  Remove:
    main: Remove.hs

  CleanupHeaders:
    main: CleanupHeaders.hs
